Updated slathering setup

diff --git a/.github/workflows/CI_macOS.yml b/.github/workflows/CI_macOS.yml
--- a/.github/workflows/CI_macOS.yml
+++ b/.github/workflows/CI_macOS.yml
@@ -18,12 +18,12 @@ jobs:
     - name: Xcode version
       run: /usr/bin/xcodebuild -version
       
-    - name: Build and Test
-      run: xcodebuild clean build test -project PodcastsComponents/PodcastsComponents/PodcastsComponents.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES -resultBundlePath CImacOSResults
-    - uses: kishikawakatsumi/xcresulttool@v1
-      with:
-        path: CImacOSResults.xcresult
-      if: success() || failure()
+    # - name: Build and Test
+    #   run: xcodebuild clean build test -project PodcastsComponents/PodcastsComponents/PodcastsComponents.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES -resultBundlePath CImacOSResults
+    # - uses: kishikawakatsumi/xcresulttool@v1
+    #   with:
+    #     path: CImacOSResults.xcresult
+    #   if: success() || failure()
 
     - name: Install Slather
       run: gem install slather
@@ -33,6 +33,7 @@ jobs:
       env:
         CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
       with:
-        coverageCommand: slather coverage -x --output-directory slather-test-output --scheme CI_macOS PodcastsComponents/PodcastsComponents/PodcastsComponents.xcodeproj
+        debug: true
+        coverageCommand: slather coverage -s --output-directory slather-test-output --scheme CI_macOS PodcastsComponents/PodcastsComponents/PodcastsComponents.xcodeproj
         coverageLocations: |
           ./slather-test-output/cobertura.xml
