Coverage publish to codeclimate

diff --git a/.github/workflows/CI_macOS.yml b/.github/workflows/CI_macOS.yml
--- a/.github/workflows/CI_macOS.yml
+++ b/.github/workflows/CI_macOS.yml
@@ -18,13 +18,13 @@ jobs:
     - name: Xcode version
       run: /usr/bin/xcodebuild -version
       
-    - name: Build and Test
-      run: xcodebuild clean build test -project PodcastsComponents/PodcastsComponents/PodcastsComponents.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES -resultBundlePath CImacOSResults -derivedDataPath /tmp/XcodeDerivedDataWithCoverage
+    # - name: Build and Test
+    #   run: xcodebuild clean build test -project PodcastsComponents/PodcastsComponents/PodcastsComponents.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES -resultBundlePath CImacOSResults -derivedDataPath /tmp/XcodeDerivedDataWithCoverage
 
-    - uses: kishikawakatsumi/xcresulttool@v1
-      with:
-        path: CImacOSResults.xcresult
-      if: success() || failure()
+    # - uses: kishikawakatsumi/xcresulttool@v1
+    #   with:
+    #     path: CImacOSResults.xcresult
+    #   if: success() || failure()
 
     - name: Slather install
       run: sudo gem install slather
@@ -32,12 +32,11 @@ jobs:
     - name: Code coverage converting to cobertura.xml format
       run: slather coverage -x
 
-    - name: Publish code coverage
+    - name: Test and Publish code coverage
       uses: paambaati/codeclimate-action@v3.2.0
       env:
         CC_TEST_REPORTER_ID: "${{ secrets.CC_TEST_REPORTER_ID }}"
       with:
-        workingDirectory: slather_reports/CI_macOS/
         debug: true
-        coverageLocations: |
-        ${{github.workspace}}/slather_reports/CI_macOS/*.xml:cobertura
+        coverageCommand: xcodebuild clean build test -project PodcastsComponents/PodcastsComponents/PodcastsComponents.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES -resultBundlePath CImacOSResults -derivedDataPath /tmp/XcodeDerivedDataWithCoverage
+        coverageLocations: ${{github.workspace}}/slather_reports/CI_macOS/*.xml:cobertura
